services:
  - type: web
    name: sisalud-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///instance/sisalud.db
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1 